covid19_analytics:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: covid19-dbt-analytics-1
      dataset: dev
      threads: 4
      location: EU
      timeout_seconds: 300